version: '3.8'

services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: alaa
    ports:
      - 3306:3306

  postgres:
    platform: linux/x86_64
    image: postgres:13.1
    restart: always
    environment:
      POSTGRES_PASSWORD: alaa
    ports:
      - 5432:5432

  adminer:
    platform: linux/x86_64
    image: adminer
    restart: always
    ports:
      - 8080:8080
